# Generated by Django 4.2.11 on 2024-03-26 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alternative',
            old_name='criteria_id',
            new_name='criteria',
        ),
        migrations.RenameField(
            model_name='alternative',
            old_name='student_id',
            new_name='student',
        ),
    ]
